services:
  - type: web
    name: certificate-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: VERIFICATION_BASE_URL
        value: https://certificate-backend-1kcb.onrender.com
      - key: NODE_ENV
        value: production
